apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"       # REQUIRED
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cron
              image: busybox
              command: ["date"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3 # optional
  failedJobsHistoryLimit: 1     # optional
  concurrencyPolicy: Forbid     # optional
