apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
spec:
  minAvailable: 1             # optional (use either minAvailable or maxUnavailable)
  selector:                   # REQUIRED
    matchLabels:
      app: my-app
