apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: my-snapshot-class

driver: csi-hostpath-driver     # REQUIRED

deletionPolicy: Delete          # optional (Delete or Retain)
parameters:                     # optional
  foo: bar
